Implement upload for xlsx file
4teamwork/ftw.linkchecker pull request #63
Opened 2019-07-08 09:34 UTC by busykoala

To access the reports we want to have the possibility to choose a filelisting block in the installation where the file is uploaded.

2019-07-16 13:15 UTC, maethu requested changes
Looks already pretty good, just two minor things.

2019-07-16 13:15 UTC, maethu commented on ftw/linkchecker/command/checking_links.py
> +    file = plone.api.content.create(container=file_listing_block, type='File', title=file_name, file=data)
Don't override pythons `file` here. You could simply use `file_`, oder `file_content_type`

2019-07-16 13:15 UTC, maethu commented on ftw/linkchecker/command/checking_links.py
> +        # TODO: log exception (this is most likely be raised if
Yes please, I would like to see if the upload fails for some reason,

2019-07-22 08:21 UTC, tinagerber commented
Okay, I've made the desired changes.

2019-07-22 14:57 UTC, maethu approved these changes

2019-07-22 14:57 UTC, merged